tags:
  - Usuario
operationId: registro
description: Registro del usuario
parameters:
  - in: body
    name: body
    schema:
      properties:
          correo:
              type: string
              example: correo@correo.com
          password:
              type: string
              example: '123456'
          nombre:
              type: string 
              example: Eduardo
          tipoUsuario:
              type: string
              enum:
                - ADMIN
                - USUARIO
          birthday:
              type: string
              examepl: 2020-01-01
responses:
  201:
    schema:
      properties:
        content:
          type: object
          properties:
            schema:
              $ref: '#/definitions/Usuario'
          
        message:
          type: string
          example: Usuario creado exitosamente
